- server: robothandsounding.house
  alt_ssl: false
- server: startpage.hometest.local
  alt_ssl: true
- server: homeblog.hometest.local
  alt_ssl: true
- server: ansible.hometest.local
  alt_ssl: true
- server: netbox.hometest.local
  alt_ssl: true
- server: relay.hometest.local
  alt_ssl: true
- server: lights.hometest.local
  alt_ssl: true
- server: tickets.hometest.local
  alt_ssl: true
- server: homewifi.hometest.local
  alt_ssl: true
- server: zabbix.hometest.local
  alt_ssl: true
- server: vcsa.hometest.local
  alt_ssl: true
- server: freenas.hometest.local
  alt_ssl: true
- server: ssltracker.hometest.local
  alt_ssl: true
